### ISSUE TITLE
BUG：设置中的“删除来自关联频道的消息”选项无法取消

### ISSUE THREAD

**Issue by tjsky** [AnotiaWang/AntiChannelSpammersBot#1]
设置中的“删除来自关联频道的消息”选项无法取消，
设置总是会自动回归默认状态：“删除来自关联频道的消息√”

**Comment by AnotiaWang** [comment]
> 设置中的“删除来自关联频道的消息”选项无法取消， 设置总是会自动回归默认状态：“删除来自关联频道的消息√”

已修复，感谢反馈！
