### ISSUE TITLE
一个新的问题，带着频道马甲发送命令会导致功能失效

### ISSUE THREAD

**Issue by moshaoli688** [AnotiaWang/AntiChannelSpammersBot#3]
一个新的问题，带着频道马甲发送命令会导致删除频道马甲的消息功能失效。
建议增加一个判断使用者是否为频道马甲在响应相关命令。。

**Comment by AnotiaWang** [comment]
你的意思是，使用马甲发送的命令不会被自动删除吗？因为都放到设置的 “自动删除命令” 那里了

**Comment by AnotiaWang** [comment]
已修复
