### ISSUE TITLE
新commit中，任何人发的任何命令都会被删除

### ISSUE THREAD

**Issue by qwerzl** [AnotiaWang/AntiChannelSpammersBot#4]
如题。所有以/开头的消息都会被删除。
如图：
[![vp6J4P.jpg](https://s1.ax1x.com/2022/07/27/vp6J4P.jpg)](https://imgtu.com/i/vp6J4P)
[![vp6GNt.jpg](https://s1.ax1x.com/2022/07/27/vp6GNt.jpg)](https://imgtu.com/i/vp6GNt)

**Comment by AnotiaWang** [comment]
应该已修复，抱歉添麻烦了

**Comment by qwerzl** [comment]
感谢🙏
