### ISSUE TITLE
启用自动清理命令功能后，路径消息也会被自动删除

### ISSUE THREAD

**Issue by bekcpear** [AnotiaWang/AntiChannelSpammersBot#5]
如题

比如开头为 `/usr/bin/env` 这种路径的消息，也会在这个功能开启的情况下被自动删除

建议是改成只清理本 bot 自己的命令，因为其它的命令如果被清理可能也会影响到其它 bot 的任务

**Comment by AnotiaWang** [comment]
这个比较难避免的，因为 Telegram 的命令机制本身就是以 `/` 开头的。

我刚刚给机器人增加了一个例外判断，您可以试试把路径用等宽包裹起来，机器人就不会去处理了。

![image](https://user-images.githubusercontent.com/62269186/188184629-8aa51e7e-59c7-480e-a94e-e2367272bc16.png)
